name: Sync Submodules to main

on:
  workflow_dispatch:        # Manual trigger
  schedule:
    - cron: '*/15 * * * *'     # Optional: daily at 6 AM UTC

jobs:
  sync-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout parent repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout 'main' in each submodule
        run: |
          for dir in dotfiles hydration infrastructure; do
            echo "🔁 Switching $dir to main..."
            cd "$dir"
            git fetch origin
            git checkout main
            git pull origin main
            cd ..
          done

      - name: Commit updated submodule SHAs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dotfiles hydration infrastructure
          git commit -m "chore(submodules): update to latest main" || echo "No changes to commit"

      - name: Push updated submodules to main
        run: |
          git push origin HEAD

